### ISSUE TITLE
No mutual exclusion enforced for MySQL backups

### ISSUE THREAD

**Issue by moretea** [autopilotpattern/mysql#17] opened 2016-04-20 13:56 UTC
The `create_backup` command does not enforce mutual exclusion of itself. If the backup is triggered in the `onhealth` hook, and this hook gets triggered again before the backup is finished, multiple backup jobs will be running concurrently.

Adding a unix file lock should prevent this from happening.

**Comment by tgross** [comment] 2016-04-20 15:41
This should be handled at the cluster level by [`set_backup_ttl`](https://github.com/autopilotpattern/mysql/blob/37825aacc6a8c94f155ff0f7f386e12235cb1dfc/bin/triton-mysql.py#L798-L821). The idea being that's it's not enough to make sure we're not running multiple backups on a node but that we want to make sure it's only running on a single node as well.

We're setting that TTL in Consul [before we run the backup](https://github.com/autopilotpattern/mysql/blob/37825aacc6a8c94f155ff0f7f386e12235cb1dfc/bin/triton-mysql.py#L791-L795) specifically for the reason you're saying here. But of course it's possible that there's a bug -- have you see this happen and can you share logs and/or configuration that reproduces it?

**Comment by tgross** [comment] 2016-04-20 19:54
I was just able to confirm this is the case with what's currently in master. Not sure how/why that regressed. Let me look into it.

**Comment by moretea** [comment] 2016-04-21 08:14
Yes, I've seen this happen. It actually created a bunch of `create_backup` processes that turned into zombies.

I think the  following execution happened: the master starts up, and executes its first health check. During this health check, it sees that `LAST_BINLOG_KEY` does not exist. Hence the call to `is_binlog_stale` in the `health` method returns true, triggering a `write_snapshot`. However, the `LAST_BINLOG_KEY` is only written *after* the snapshot is taken. So if the process of spawning a new process to make the  snapshot takes longer than the health interval, multiple of these snapshot creation jobs can run.

**Comment by tgross** [comment] 2016-04-21 12:26
Ok, I can confirm that. It looks like my reasoning here was that `is_binlog_stale` is getting called during the health check and that key will have been written. But the *first* time we call `is_binlog_stale` we'll always consider the binlog stale and so each time the health check fires it's going to attempt the snapshot again. Not sure how this got missed in the first pass because it seems like an obvious bug. 😊 

I'm going to spend a bit of time on this this morning.

**Comment by tgross** [comment] 2016-04-21 14:36
@moretea I've dropped a fix into https://github.com/autopilotpattern/mysql/pull/20 and it's been merged. Want to give that a try?

**Comment by tgross** [comment] 2016-04-22 00:24
Gah... I've had a chance to test that better in https://github.com/autopilotpattern/mysql/pull/21 and it won't work like that either.

**Comment by tgross** [comment] 2016-04-22 13:59
https://github.com/autopilotpattern/mysql/pull/21 has been updated with this fix.

**Comment by tgross** [comment] 2016-04-22 14:18
Closed with #21

**Closed by tgross** 2016-04-22 14:18 UTC
Labels: bug
