### ISSUE TITLE
How to AutoScale

### ISSUE THREAD

**Issue by Smithx10** [autopilotpattern/mysql#54] opened 2016-09-06 15:57 UTC
So I've gone through all the demos and am understanding how this all works,  my question now is... how do I docker-compose scale customers=+1 or -1 on the fly? I would like to use some type of metric to autoscale.  I don't know if this was the correct place to ask this,  is there a mailing list?

**Comment by tgross** [comment] 2016-09-06 17:02
We have an open issue to implement telemetry hooks https://github.com/autopilotpattern/mysql/issues/16. The operator would then get use information provided by the ContainerPilot telemetry endpoint to feed into whatever is scaling the instances (presumably not Compose but whatever lightweight scheduler you might be using).

**Comment by Smithx10** [comment] 2016-09-06 17:15
Which Scheduler fits the Triton ecosystem best?  Any suggestions?

**Comment by tgross** [comment] 2016-09-08 12:57
Unfortunately the Docker-ecosystem community has largely gone the route of "giant mega-orchestrator" over "lightweight scheduler." In the meantime, we've seen workable results with [Mesos](https://www.joyent.com/blog/mesos-by-the-pound), and at least one Triton Enterprise customer is driving Compose via their CI/CD systems (this is more-or-less how Joyent's own web properties are deployed). In the near future ["Mariposa"](https://github.com/joyent/rfd/blob/master/rfd/0036/README.md) will be the best choice.

**Comment by misterbisson** [comment] 2016-09-12 02:59
@Smithx10: one of the first questions to answer here is what metric(s) we'll use to determine when to scale up or down. [ContainerPilot 2.0 introduced a telemetry feature](https://www.joyent.com/blog/containerpilot-telemetry) specifically to support the monitoring of key metrics that can help determine scaling. I opened https://github.com/autopilotpattern/mysql/issues/16 to implement that for MySQL in this repo.

Feedback, suggestions, or pull requests in https://github.com/autopilotpattern/mysql/issues/16 would be greatly appreciated.

**Comment by misterbisson** [comment] 2016-09-12 03:11
Closing as a duplicate of https://github.com/autopilotpattern/mysql/issues/16. Please continue the conversation there.

**Closed by misterbisson** 2016-09-12 03:11 UTC
Labels: duplicate
