### ISSUE TITLE
manage.py is writing invalid value for the innodb_buffer_pool_size

### ISSUE THREAD

**Issue by headw01** [autopilotpattern/mysql#33] opened 2016-05-23 16:29 UTC
manage.py is writing the innodb_buffer_pool_size out as MB.  According to the MySQL documentation, this numeric value is in Bytes.  On a 4GB server, manage.py writes out 2867.  This is below the minimum value (see doc below).  Since the value written is below the minimum, the min value (5MB) is used.  This can be verified by looking at the docker log for the instance as it is created.

2 fixes from my point of view:
1) Change manage.py to calculate the value in Bytes instead of MB.
or
2) Change my.cnf.tmpl $buffer substitution to include the units like this: `innodb_buffer_pool_size = ${buffer}M`

https://dev.mysql.com/doc/refman/5.6/en/innodb-parameters.html#sysvar_innodb_buffer_pool_size

**Comment by tgross** [comment] 2016-05-23 17:05
Closing as a dupe of https://github.com/autopilotpattern/mysql/issues/32

**Closed by tgross** 2016-05-23 17:05 UTC
